# Generated by Django 3.0.4 on 2020-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiluser',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
