version: '3'

services:
  db:
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django:
    build: .
    volumes:
      - .:/opt/basil
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: