apiVersion: apps/v1
kind: Deployment
metadata:
  name: basil-core-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: basil-core
  template:
    metadata:
      labels:
        component: basil-core
    spec:
      containers:
        - name: basil-core
          image: dosatross/basil_dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: BASIL_DB_HOST
              value: basil-postgres-clusterip
            - name: BASIL_DB_NAME
              value: basil
            - name: BASIL_DB_USER
              value: basil_user
            - name: BASIL_DB_PORT
              value: '5432'
            - name: BASIL_DB_PW
              valueFrom:
                secretKeyRef:
                  name: basil-core-secret
                  key: BASIL_DB_PW
            - name: BASIL_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: basil-core-secret
                  key: BASIL_SECRET_KEY