# Generated by Django 2.1.5 on 2019-01-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190115_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'subcategory']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_earned',
        ),
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(related_name='categories', to='categories.CategoryGroup'),
        ),
    ]
