# Generated by Django 2.1.7 on 2019-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190206_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='categories', to='categories.CategoryGroup'),
        ),
    ]
